[workspace]
members = [
    "solana-adapter",
    "dac-sdk",
    "compute-node",
    "validator-node",
]
resolver = "2"

[workspace.dependencies]
tokio = { version = "1.49.0", features = ["full"] }
solana-sdk = "3.0.0"
anyhow = "1.0.100"
